// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Your2DWorld",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "Your2DWorld",
            targets: ["AppModule"],
            bundleIdentifier: "com.heri.Your2DWorld",
            teamIdentifier: "843V7URJY9",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "Permission is required for the app to run"),
                .photoLibraryAdd(purposeString: "Permission is required for the app to run")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)